set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER /home/tyg13/bin/xgcc-9.2.0/bin/x86_64-tyleros-gcc)
set(CMAKE_CXX_COMPILER /home/tyg13/bin/xgcc-9.2.0/bin/x86_64-tyleros-g++)

set(CMAKE_FIND_ROOT_PATH /home/tyg13/bin/xgcc-9.2.0/)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)
