set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER "$ENV{XGCC_BIN}/x86_64-elf-gcc")
set(CMAKE_CXX_COMPILER "$ENV{XGCC_BIN}/x86_64-elf-g++")
set(CMAKE_LINKER "$ENV{XGCC_BIN}/x86_64-elf-ld")
set(CMAKE_AR "$ENV{XGCC_BIN}/x86_64-elf-ar")
set(CMAKE_RANLIB "$ENV{XGCC_BIN}/x86_64-elf-ranlib")
set(CMAKE_OBJCOPY "$ENV{XGCC_BIN}/x86_64-elf-objcopy")
set(CMAKE_STRIP "$ENV{XGCC_BIN}/x86_64-elf-strip")

set(CMAKE_FIND_ROOT_PATH /home/tyg13/bin/xgcc-9.2.0/)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)
